package exceptions.myTest;

public class ExceptionTest {



    public static void main(String[] args) {
    int i=1;
//        try {
            System.out.println((i / 0));
//        } catch (Exception e) {
//            System.out.println("2233");
//        }
        System.out.println(33344);
    }
}
