package exceptions.myTest;

public class Test2 {

    public static void main(String[] args) {

        int i = 2;
//        try {
            i = 1 / 0;
//        } catch (Exception e) {
//
//            System.out.println(i);
//        }
        System.out.println(i);
        System.out.println(4/2);


    }
}
